# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "platform-releases"

  config.vm.provider "virtualbox" do |v, override|
    v.gui = false
    v.customize ["modifyvm", :id, "--memory", 1024]
    v.customize ["modifyvm", :id, "--cpus", 1]
  end

  config.vm.synced_folder "../", "/ohana"

  $script = <<SCRIPT
sudo apt-get update && sudo apt-get install --yes pandoc
SCRIPT

  config.vm.provision "shell", inline: $script
end
